[
  { q:"Which three prices inside an order block candle are called sensitive?", o:["The low, the open and the 50% level","The high, the close and the wick tip","The open, the close and the volume node","The prior close, the low and the gap edge"], a:0, e:"When using a candle as an order block, the low, the open and the middle of its range are the three sensitive areas being watched." },
  { q:"What is the mean threshold of an order block?", o:["The 50% level of that candle's range","The candle's opening price","The midpoint between two order blocks","The average of the session's highs"], a:0, e:"The middle of the candle — found by running a fib across it to the 50 level — is what he calls the mean threshold." },
  { q:"What does trading through the mean threshold suggest about that order block?", o:["It is likely to fail and price continues","It has been confirmed and will hold","It becomes a target rather than a level","It should be redrawn one timeframe lower"], a:0, e:"The mean threshold being taken bodes well for a continuation to take out the short-term high; if it doesn't hold, expect the order block to fail." },
  { q:"A price leg was delivered in two stages. Which one frames the dealing range?", o:["The most recent stage","The first stage of the two","Both stages combined as one range","Whichever stage is longer in points"], a:0, e:"\"Because I had two stages to this delivery, I want to use this most recent one — and this is my dealing range.\"" },
  { q:"When plotting a correlated contract to spot SMT, what setting must be changed?", o:["Plot on the low instead of the close","Switch the chart from candles to bars","Set the session to include extended hours","Change the currency to match the base"], a:0, e:"The compare symbol defaults to plotting on the close; change it to plot on the low, because you are comparing lows." },
  { q:"At what times is the cracking correlation said to show up?", o:["8:30, 9:30 and on news releases","Only at the daily close","Randomly, with no time pattern","During the lunch hour exclusively"], a:0, e:"The two markets usually move in tandem, and create the divergence at certain times — 8:30, 9:30, and at news events being released." },
  { q:"Why is SMT divergence unreliable without a bias?", o:["It can vanish as they re-correlate","It only prints on weekly charts","It always reverses within one candle","It requires three markets to confirm"], a:0, e:"Without knowing where price is going you will often see what looks like SMT divergence and then it disappears as the two start moving in concert again." },
  { q:"An early run before seven o'clock in the morning suggests what next?", o:["A deep retracement, then SMT near 9:30","An immediate continuation with no pullback","A flat session with no further move","An early close of all open positions"], a:0, e:"A nice run before or at seven means a deep retracement is probably coming, and SMT usually occurs around the 9:30 period to set up the next leg." },
  { q:"Why was a short into the range above judged unlikely to work?", o:["It would be a high resistance liquidity run","Shorts are banned above the daily open","There was no order block to sell from","The session had already closed for news"], a:0, e:"Price running straight up through all that range is a high resistance liquidity run — not impossible, but unlikely to pan out with bullish order flow supporting price." }
]
