[
  { q:"In a bearish fair value gap, what marks its upper end?",
    o:["The low of candle number one",
       "The high of candle number one",
       "The close of candle number two",
       "The open of candle number three"],
    a:0,
    e:"The upper end of the fair value gap is candle number one's low and the lower end is candle number three's high; candle number two is where the gap resides. The difference between those two prices is the gap itself." },

  { q:"What must candle three do for the formation to be valid?",
    o:["Trade to an extended low below candle two",
       "Close lower than candle two closed",
       "Trade back up into candle one's low",
       "Print a larger body than candle two"],
    a:0,
    e:"Candle three has to trade with an extended low that went below candle two, and it must not trade with a high that reaches back into candle one's low — that overlap is what would erase the gap." },

  { q:"What is the paint-roller analogy explaining?",
    o:["Price returning to rebalance an inefficient area",
       "Why volume thins out at the end of a trend",
       "How stops accumulate above a series of highs",
       "Why the first hour of the day is unreliable"],
    a:0,
    e:"Rolling paint down a wall leaves porous pockets, and you fix them by changing direction and rolling back up over the same place. Inside the gap price was only offered on the sell side, so the algorithm will want to trade back into that area to balance it out." },

  { q:"Where must the fair value gap form for the trade to exist?",
    o:["Between the displacement high and displacement low",
       "Anywhere inside the previous trading session",
       "Directly above the old high that was raided",
       "Between the session open and the 50% level"],
    a:0,
    e:"After a run above an old high and an energetic break below a short-term low, that broken low is the displacement low and the swing high is the displacement high. You hunt the gap in that range — if there is no gap in there, you don't have a trade." },

  { q:"What makes a break of the short-term low convincing?",
    o:["An energetic move that closes below the low",
       "A wick that pierces the low and snaps back",
       "A close back above the old high afterwards",
       "A rise in volume on the breakdown candle"],
    a:0,
    e:"\"Quick\" is linked directly to displacement: it has to be energetic, showing a real willingness to go lower, and preferably closing below that low. Just running through the low like a wick and coming back up is not all that convincing." },

  { q:"How does the first run at the 9:30 equity open usually behave?",
    o:["Opposite to the real move you want",
       "In line with the overnight session's trend",
       "Flat until the 10:00 data release",
       "Straight into the previous day's close"],
    a:0,
    e:"Usually — not always — the first run at 9:30 is opposite to the real move you want to be doing. That volatility built lows with sell stops under them, inducing traders into longs while leaving the buy-side highs above intact." },

  { q:"What separates internal from external range liquidity here?",
    o:["Internal sits inside the range; external is stops beyond it",
       "Internal is intraday liquidity; external is overnight",
       "Internal means index futures; external means cash",
       "Internal is your partial; external is your stop loss"],
    a:0,
    e:"With a fib on the low-to-high run, the opposite fair value gap below equilibrium is internal range liquidity — internal relative to that low and high — while the sell stops resting below the lows are external range liquidity. Partials at the internal, the balance at the external." },

  { q:"When may the protective stop be rolled down?",
    o:["Once a significant intermediate-term low is taken out",
       "As soon as the first partial has been booked",
       "After each new one-minute candle closes lower",
       "The moment the trade reaches breakeven"],
    a:0,
    e:"Use the first partial to quench the desire to roll your stop. Only after a significant intermediate-term low has been taken out can you move it there — trailing it aggressively before that is how those upsetting pullbacks knock you out before the real move." }
]
