[
  { q:"What creates an intermediate term high or low?", o:["Price rebalancing an old imbalance","Any swing that breaks a trend line","The highest volume bar of the session","Three consecutive same-colour candles"], a:0, e:"Every single time price rebalances an imbalance, the swing created at that moment is immediately classified as an intermediate term high or low." },
  { q:"An intermediate term high sits lower than the short-term highs beside it. What does that say?", o:["The market is weak and only rebalancing","The high is invalid and should be redrawn","A bullish reversal is now confirmed","Volatility is too low to trade the session"], a:0, e:"Ideally the ITH is above both short-term highs. When it is not, the market is very weak and the algorithm is tipping its hand — it is only rebalancing the imbalance." },
  { q:"What is his definition of an order block?", o:["The consecutive series of up close candles","The last up close candle before the drop","The candle holding the highest volume","Any candle that leaves a fair value gap"], a:0, e:"He is emphatic that the order block is one consecutive series of up close candles, not the last up close candle before the down move, and that you hunt fair value gaps inside that range." },
  { q:"Which question does he ask before sitting down at the charts?", o:["Is price going for stops or to rebalance?","Which harmonic pattern is completing here?","Where are the moving averages about to cross?","Which Elliott wave count fits this leg best?"], a:0, e:"The number one question is the current market narrative: is price likely to go up or down for stops, or up or down to rebalance an imbalance. Nothing attributable to a retail mindset." },
  { q:"Where does he anchor the Fibonacci for a downside projection?", o:["Intermediate term high to long-term low","Long-term high to the most recent low","Session open to the session high","The fair value gap high to its low"], a:0, e:"The retracement that fails is where the decline begins, so the anchor is that intermediate term high down to the long-term low, with the −1.5 standard deviation giving the projection." },
  { q:"In a bearish price swing, what role do up close candles play?", o:["Resistance that price should stay below","Support that price should bounce off","Confirmation that the trend has ended","Neutral candles with no structural use"], a:0, e:"Institutional order flow: in bearish swings up close candles are your resistance and act as speed bumps; you do not want to see price trade above them." },
  { q:"What should you do when an intermediate term high is violated against your idea?", o:["Go to the sidelines and wait for sync","Add to the position at a better price","Flip the bias and trade the other way","Move the stop up and hold for longer"], a:0, e:"If the next short-term high trades above that intermediate term high your idea is probably flawed. Don't force it — wait for market structure to get back in sync with what you expect." },
  { q:"Which timeframe does he call the bellwether for the actual entry?", o:["The 15-minute","The 1-minute","The 4-hour","The daily"], a:0, e:"The daily supplies the logic, the hourly frames the trade, and the 15-minute is the bellwether that gives the actual get in and get out — lower only if the risk parameters don't suit." },
  { q:"What two principles does he say the market books candles on?", o:["Liquidity, and imbalance or rebalance","Supply and demand at key price levels","Volume profile and the value area","Interest rates and trader sentiment"], a:0, e:"His answer to the riddle of competing disciplines: price runs above old highs for buy stops or below old lows for sell stops, and it creates or rebalances imbalance. That is all it does." },
  { q:"Why does price return into a one-sided single-candle move?", o:["To offer buyers a chance at those prices","Because stops always sit at its midpoint","To confirm the pattern for retail traders","Because exchanges require a daily retest"], a:0, e:"It went down too quickly with no give and take, so it goes back up to offer buyers an opportunity at those prices. The algorithm is allowing efficiency for price delivery, whether or not those buyers are right." }
]
