[
  { q:"What makes a market trading above an old high a premium?", o:["It has moved up into liquidity","It has closed above equilibrium","Its indicators read overbought","It has left an unfilled gap behind"], a:0, e:"\"Any time the market trades above an old high, that is a short-term premium, because it's going into liquidity\" — and below an old low is a discount, by the same reasoning." },
  { q:"What is it telling you when the candle bodies stay inside a fair value gap?", o:["High probability — volume is held there","The gap has been invalidated","A stop run is about to fail","The imbalance must be redrawn"], a:0, e:"Price reaches for liquidity on the wicks, but the bulk of the volume is held inside the imbalance. If the bodies respect the gap, \"that says a lot, that's high probability.\"" },
  { q:"NQ makes a higher run but ES does not, and you are bearish. What is that?", o:["A stop run showing ES is weak","A sign the correlation has ended","A signal to buy the weaker index","An indicator divergence to confirm"], a:0, e:"These closely correlated composites usually move in tandem, so the one-sided run is a stop run — it shows ES is really weak, giving confirmation without an indicator. That is distribution." },
  { q:"How should a large position be pyramided?", o:["Biggest size first, then smaller and smaller","One contract at a time, adding evenly","Smallest first, scaling up as it works","All at once at the mean threshold"], a:0, e:"\"When I pyramid and I build in large positions I'm starting with my biggest position first and then I'm going smaller and smaller until I can't do any smaller\" — never one, then one more, then one more." },
  { q:"Two fair value gaps sit above your entry gap. What does that change?", o:["Expect a stab into the upper one","Move the entry up to the upper gap","Halve the target and exit sooner","Nothing — the stop stays the same"], a:0, e:"With only one gap you place your entry and don't expect a deeper retracement; with a second one above, expect price to stab up into it, so the stop must be able to weather that — or trade the micros." },
  { q:"Which price points does he anchor the fib to for optimal trade entry?", o:["The bodies — lowest and highest open or close","The absolute wick high and wick low","The midnight open and the 8:30 open","The gap's high and its mean threshold"], a:0, e:"For OTE he uses the bodies — the lowest open or close in one swing and the highest in the other — \"it's the bulk of the volume.\" The wicks beyond them are treated as stop runs." },
  { q:"Which two fib levels make up the optimal trade entry?", o:["The 62 and the 79","The 50 and the 62","The 70.5 and the 79","The 79 and the 88"], a:0, e:"He plots the 0.62 and 0.79 retracement levels as the optimal trade entry, with 0.5 marking equilibrium — the divide between premium and discount." },
  { q:"Why does he re-engage the market around 1:30pm?", o:["Lunch is smoothed out and a retracement follows","Volume peaks at the afternoon open","Stops reset after the 11:30 cut-off","The daily range is redrawn at that hour"], a:0, e:"After 1:30 the lunch hour has been smoothed out, and there is usually a retracement higher when bearish or lower when bullish — an area to get short or long into." },
  { q:"What defines an intermediate term high?", o:["It has an imbalance at it","It is the highest of three swings","It forms inside the killzone","It sits above the opening price"], a:0, e:"Both highs in the example are intermediate term highs \"because they have imbalances\" — an ITH leaves behind imbalance. How they nest then decides which is the long term high." }
]
