[
  { q:"Before the new trading week begins, which question sets your initial bias?",
    o:["Where the weekly candle is likely to close out",
       "What price is most likely to draw towards next",
       "Which session will carry the highest volume",
       "Whether last week's candle closed up or down"],
    a:1,
    e:"You are not trying to predict the weekly candle's close — only which end it is likely to expand toward. Ask what price is most likely to draw towards: is there an imbalance higher, or a liquidity pool lower? That sets the initial bias for the week." },

  { q:"When a significant move lower is expected, what should you anticipate first?",
    o:["A stop hunt taking out buy stops above a high",
       "A retest of the previous day's closing price",
       "A drop in volume through the London session",
       "A sell stop run beneath the weekly opening"],
    a:0,
    e:"Record this in your notes: any time a significant price move lower is expected, always anticipate some measure of stop hunt on buy stops — a short-term high being taken out — before the move. It is reversed when you expect higher prices." },

  { q:"Why does the algorithm drive price up into buy stops before selling off?",
    o:["It supplies buyers at a high price to sell into",
       "It confirms the resistance level has held firm",
       "It rebalances the volume traded on both sides",
       "It resets the range so the fib can be redrawn"],
    a:0,
    e:"Running the buy stops sends them into the market as market orders — a huge influx of willing buyers at a high price, which is the perfect counterparty for smart money that wants to sell short at a high price." },

  { q:"Which timeframes are best for finding imbalances on the indices?",
    o:["The 1-, 2- and 3-minute charts",
       "The 15- and 30-minute charts",
       "The 4-hour and daily charts",
       "The 30- and 60-second charts"],
    a:0,
    e:"The 1-, 2- and 3-minute charts tend to be the best for finding the imbalances on indices, because the high-frequency trading algorithms operate at nothing really higher than three minutes. The 5-minute still leaves a lot of room for imbalances underneath it." },

  { q:"Where do the entry, stop and exit sit on this setup?",
    o:["Enter in the FVG, stop above the candle over it, exit at the liquidity",
       "Enter at the swing high, stop at the day's open, exit at the 50% level",
       "Enter once the low breaks, stop below the gap, exit on the next close",
       "Enter on the retest, stop at the session high, exit at the daily close"],
    a:0,
    e:"Enter in the fair value gap, place the stop above the candle above the gap (or above the swing high that was run, as your risk parameters allow), and exit where the liquidity is." },

  { q:"Price is trading above the 50% of the day's range. What is that?",
    o:["A premium market — expensive, where you can sell",
       "A discount market — cheap, where you look to buy",
       "A balanced market — no trade until it breaks out",
       "An expanded market — the range is already spent"],
    a:0,
    e:"Split the range from the low to the high with a Fibonacci and watch the 50% level. Anything above it is a premium — expensive — so the algorithm's opposing side of the market is the discount below it. Aim for the low hanging fruit down there: the closest old low or imbalance." }
]
