[
  { q:"Why did he refuse to trade through the morning session?", o:["He wanted the 3915.25 level broken first","He was waiting for the 8:30 news to clear","The spread was too wide to justify a fill","He had already used up the day's risk"], a:0, e:"\"I didn't want to do anything prior to this run\" — nothing interested him until that low was taken out, since price could equally have shown a willingness to run the highs above instead." },
  { q:"Why not simply trade the earlier short-term lows breaking?", o:["Above it the 15-minute is merely consolidated","Those lows sat outside the killzone window","The imbalance had already been rebalanced","Short-term lows never hold sell-side liquidity"], a:0, e:"You could, if you want to be ultra aggressive — but with this much volatility he wants to know that he knows, and above that level the 15-minute is consolidated, risking a break below a short-term low that then runs the relative equal highs." },
  { q:"What does he need present before trusting a broken old low?", o:["A fair value gap formed with the break","A close beyond it on the daily chart","A second test of the level within an hour","Higher volume than the previous session"], a:0, e:"\"If the fair value gap doesn't exist, I don't trust that level as an old support broken turned resistance\" — the gap after the run below is the trade, not the level itself." },
  { q:"How does he distinguish his levels from support and resistance?", o:["They mark liquidity, classified in advance","They are drawn only after price reacts to them","They come from a fixed percentage grid","They are the highs and lows of each session"], a:0, e:"\"They're levels built on the logic, and it's based on liquidity, not support and resistance — the orders I know are going to be there\" — classified beforehand on the logic that the market creates patterns around them." },
  { q:"What conditions had to stack up for the 3855 objective to be reached?", o:["A break plus a gap, then another break and gap","A single close below the previous week's low","Three consecutive down-close daily candles","A premium entry followed by a session reversal"], a:0, e:"Price reaches 3855 only if it breaks below the level and forms a fair value gap, then breaks the next level and gets another gap that delivers further — \"a confluence, not just one thing.\"" },
  { q:"Why did he not expect the displacement leg to reach a premium?", o:["The market was hurrying down to 3855 that week","Premiums only form in the morning session","The leg was too short to have an equilibrium","A premium had already been traded that day"], a:0, e:"He measured the leg and agreed it didn't reach a premium — he didn't expect it to, because price was in a hurry to get down below the 3855 level for the week." },
  { q:"What does he say is lost if he supplies an example of the model every day?", o:["The discovery, and your own pattern recognition","The compliance protection paper trading gives","The element of surprise the algorithm needs","The chance to trade the same setup live"], a:0, e:"Doing it for you takes away the discovery — you have to find them in your own charts, and building a backlog of old data builds confidence and your own pattern recognition. That collecting is back testing." },
  { q:"What caveats does he attach to his son's live account results?", o:["Not typical, not promised, and he sits beside him","That the account is actually a demo, not live","That the trades were entered on his behalf","That the gains came from a single trade"], a:0, e:"The account grew to $13,451.66, but he states that kind of return is not typical, promises nobody the same, notes AMP's leverage differs from leaderboard accounts, and adds that his son has a lot of experience sitting next to him." }
]
