[
  { q:"Why did he refuse to trade through the morning session?", o:["He wanted the 3915.25 level broken first","He was waiting for the 8:30 news to clear","The spread was too wide to justify a fill","He had already used up the day's risk"], a:0, e:"\"I didn't want to do anything prior to this run\" — nothing interested him until that low was taken out, since price could equally have shown a willingness to run the highs above instead." },
  { q:"Why not simply trade the earlier short-term lows breaking?", o:["Above it the 15-minute is merely consolidated","Those lows sat outside the killzone window","The imbalance had already been rebalanced","Short-term lows never hold sell-side liquidity"], a:0, e:"You could, if you want to be ultra aggressive — but with this much volatility he wants to know that he knows, and above that level the 15-minute is consolidated, risking a break below a short-term low that then runs the relative equal highs." },
  { q:"What does he need present before trusting a broken old low?", o:["A fair value gap formed with the break","A close beyond it on the daily chart","A second test of the level within an hour","Higher volume than the previous session"], a:0, e:"\"If the fair value gap doesn't exist, I don't trust that level as an old support broken turned resistance\" — the gap after the run below is the trade, not the level itself." },
  { q:"How does he distinguish his levels from support and resistance?", o:["They mark liquidity, classified in advance","They are drawn only after price reacts to them","They come from a fixed percentage grid","They are the highs and lows of each session"], a:0, e:"\"They're levels built on the logic, and it's based on liquidity, not support and resistance — the orders I know are going to be there\" — classified beforehand on the logic that the market creates patterns around them." },
  { q:"What conditions had to stack up for the 3855 objective to be reached?", o:["A break plus a gap, then another break and gap","A single close below the previous week's low","Three consecutive down-close daily candles","A premium entry followed by a session reversal"], a:0, e:"Price reaches 3855 only if it breaks below the level and forms a fair value gap, then breaks the next level and gets another gap that delivers further — \"a confluence, not just one thing.\"" },
  { q:"Your entry sits at equilibrium of the short-term range. Premium?", o:["Yes — equilibrium or above is premium","No, premium starts well above it","Only if a gap forms alongside it","Only on the higher timeframes"], a:0, e:"Framed against the short-term dealing range — that swing high to that swing low — the entry is at or above equilibrium, and equilibrium or above is a premium. The level highlights where the liquidity is; the imbalance is what is being keyed off." },
  { q:"The close ran into a random-looking level. Was it random?", o:["No — it was marked on the hourly","Yes, the close is always random","It was a round-number magnet","It was the prior day's midpoint"], a:0, e:"The close ran 'up into a completely random level' — random-looking, except that it had already been marked on the hourly chart, which is the whole point of marking it." },
  { q:"Why didn't price simply stop at the level below?", o:["It was going into the imbalance beyond","Levels only work on the daily chart","The stop orders had all been filled","It always overshoots by ten handles"], a:0, e:"That is why price didn't simply stop at the level — it was going into the imbalance beyond it before delivering lower. The gap is the trade, not the level itself." }
]
