[
  { q:"How does he define the morning session for New York index futures?", o:["8:30am to noon New York time","9:30am to the 4:00pm close","Midnight to the 9:30am open","7:00am to the London close"], a:0, e:"The day splits at the New York lunch hour, noon to 1:00pm. 8:30am to noon is the morning session; the afternoon follows lunch." },
  { q:"When trading index futures, which opening prices does he note?", o:["Midnight and the 8:30am candle open","Only the 9:30am equities open","The Sunday open and the daily close","The London open and the midnight open"], a:0, e:"There are two: midnight New York time, and the opening price of whatever candle begins at 8:30am. The candle's timeframe doesn't matter — one minute, fifteen, hourly." },
  { q:"If you are bearish, what do you want to see price do against the opening price?", o:["Trade above it as manipulation","Gap below it and never return","Close exactly on it at 9:30","Consolidate tightly around it all day"], a:0, e:"The run above a key level while bearish is the manipulation — market protraction, a Judas swing, price going the opposite way to where it is likely to go later in the day." },
  { q:"Where does he anchor the fibonacci for a swing projection?", o:["The highest and lowest candle bodies","The extreme wick high and wick low","The session open and session close","The midpoint of the opening range"], a:0, e:"Highest body (open or close) to lowest body. \"I'm showing you how the algorithm is going to read the price — the wicks and the tails are all distractions.\"" },
  { q:"Of the two projected downside levels, why did he choose 4501.25?", o:["It sat just below the daily bullish order block","It was the round number nearest the open","It was the deeper of the two projections","It matched the prior week's closing price"], a:0, e:"4501.25 sat just below the daily bullish order block at 4504, with relative equal lows above it — the measurement only mattered because the rest of the narrative agreed. That level was exactly the day's low." },
  { q:"What is his rule about the noon–1:00pm lunch hour?", o:["No entries, but partials can be taken","No trading activity of any kind","Entries allowed, but no exits","Only reversal trades are permitted"], a:0, e:"He doesn't want entries during the lunch hour, but a limit at the order block can fill during it — once you've funded the trade with a partial and moved the stop to breakeven, you don't need to babysit it." },
  { q:"When does an old high act as support?", o:["Once price has traded above it, making it a discount array","Whenever it is tested a third time","Only if it formed in the prior session","Any time the trend is upward"], a:0, e:"Old highs are a premium array; trade above one and it becomes a discount array. That is when a broken old high can act as support — \"not all the time,\" and only with the narrative that price is drawing to buy stops above. Once the liquidity target is met, stop using it." },
  { q:"How does the market engineer buy-side liquidity after taking relative equal lows?", o:["Retail reads support broken and sells the retrace","It gaps higher to trigger resting buy stops","Market makers widen the spread at the low","Volume dries up until buyers step in"], a:0, e:"Taking the relative equal lows into the order block sells retail on \"support broken,\" so they sell when price returns to those lows — those sellers become the counterparty for smart money buying. That is buy-side liquidity engineered on the basis of sell-side flow." },
  { q:"What does he say back testing is actually for?", o:["Discovery that proves the concepts repeat","Producing a precise win-rate statistic","Optimising your stop and target sizes","Proving your model before your first trade"], a:0, e:"\"You're not trying to do things correctly in back testing. Back testing is you in a mode of discovery that proves efficacy.\" Everyone does it wrong at the beginning; if you can't see it repeating, return to the core content lessons." },
  { q:"How does he say you should pyramid a position?", o:["Largest size first, then smaller adds","Smallest first, doubling on each add","Equal size on every scale-in","One contract only, never scaled"], a:0, e:"Five, then three, then two, rolled up into the objective — the biggest position first builds equity with velocity. Buying one, then two, then four, then eight is reckless: \"I've roasted accounts doing it.\"" },
  { q:"How many trades a day does he cap himself at?", o:["Four — two in the morning, two in the PM","Two — one per session, maximum","Six, spread evenly across the day","No cap, as long as setups appear"], a:0, e:"The four-trade cap, split two in the morning session and two in the afternoon, was the comment he was answering — a viewer doubted you could even find that many examples in a week." }
]
