[
  { q:"What made a long acceptable even though it fought the daily bias?", o:["Sell side was taken and a fair value gap traded into","The daily candle had already closed bullish","A moving average crossover fired on the hourly","Volume was heavier on up candles than down"], a:0, e:"The trade is taken on the basis of the sell stops already being taken and price having traded into a fair value gap around the 4000 level, leaving buy stops above the day's high as the draw." },
  { q:"What does he say the profit-and-loss figure on the screen is?", o:["A distraction — pay attention to the price","The fastest read on whether the bias is right","A required part of practising tape reading","The trigger for adding the next contracts"], a:0, e:"\"Try not to worry about that profit and loss — that's the distraction. Pay attention to the price.\" The demo position is only shown because people like to see it." },
  { q:"Where two down-close candles sit together, which one is annotated?", o:["The higher of the two, using its opening price","The lower of the two, using its closing price","Whichever candle has the larger body","Both together, measured from wick to wick"], a:0, e:"He draws the order block on the higher of the two down-close candles and uses its uppermost opening price as the level, allowing that price might only touch the higher wick — or not reach it at all." },
  { q:"Why is the stop placed underneath that particular low?", o:["It sits in the gap's lower end at an old high","It is the widest stop the account can carry","It matches the previous day's closing price","It is exactly one handle below the entry fill"], a:0, e:"The stop sits inside the lower end of the fair value gap and at the old short-term high around 9:30, so market structure supports the idea — and sell-side liquidity has already been taken out." },
  { q:"How does he describe retail's read of the drop into the equal lows?", o:["They see a bear flag and expect lower prices","They see a double bottom and buy the level","They see exhaustion and stand aside entirely","They see an overbought reading and go short"], a:0, e:"\"Retail sees that as a bear flag, so they're thinking lower prices — I'm not.\" The same inversion happens later with traders selling the rebalanced 8:30 imbalance." },
  { q:"What is a \"caffeine bar\" in his terminology?", o:["A big green candle showing fast delivery","A gap left open between two session ranges","The candle that closes the London killzone","A bar with equal upper and lower wicks"], a:0, e:"He names big green candles caffeine bars: \"if I'm bullish I want to see that; if I'm bearish I see it, I don't like it\" — the speed of delivery is the confirmation being read." },
  { q:"How is the stop handled once the trade moves in his favour?", o:["Moved up slowly, not rushed to break even","Pulled to break even on the very next candle","Removed entirely once four contracts are off","Widened to allow for the news at 10 o'clock"], a:0, e:"\"Notice I'm not in a hurry to rush my stop-loss up\" — it moves up only a little under the low first, and reaches break even only once price has expanded away." },
  { q:"How was the six-contract position finally closed out?", o:["Four sold above buy side, two stopped out","All six at market on the 4051.25 target","Four at the target, two held overnight","Two scaled out, four closed at the session end"], a:0, e:"Four contracts were closed at market above the buy-side liquidity, and the raised stop-loss then tripped out the final two, booking over five thousand hypothetical dollars." }
]
