[
  { q:"Which chart is called the bellwether for the shift that sets up the afternoon?", o:["The 15-minute chart","The 1-minute chart","The 4-hour chart","The daily chart"], a:0, e:"The 15-minute is described as \"our bellwether chart\" — its short-term shift, the fair value gap it leaves, and the return into that gap set the stage for the afternoon trend." },
  { q:"The objective failed and the market reversed without a shorting setup. What justified flipping bias?", o:["A 15m MSS whose gap was respected","The clock reaching the lunch hour","A moving average crossing back up","The failure of the objective alone"], a:0, e:"Price failed the objective, shifted structure on the 15-minute, created a fair value gap and traded back into it and repelled — that is enough to set up the afternoon trend." },
  { q:"How does his view differ from teaching liquidity voids?", o:["Imbalances need not fully rebalance","Imbalances always rebalance completely","Voids only matter on weekly charts","Voids should be ignored entirely"], a:0, e:"\"There are times when that can occur, but because I understand the algorithm, that is not likely to occur most times\" — he is not insisting the imbalance completely rebalances." },
  { q:"How is narrative defined?", o:["What price should do, why, and what proves it","The pattern that repeats every session","The consensus view of other traders","The sum of the day's economic releases"], a:0, e:"\"Narrative is the understanding of what price should do, why, and what things it will encounter to prove that the narrative you are assuming is in fact underway.\"" },
  { q:"Price retraced into lunch instead of consolidating. What does that indicate?", o:["They will work through the lunch hour","The day's range is already finished","A reversal of the morning direction","A news release is about to hit"], a:0, e:"A retracement rather than a consolidation into lunch signals a fast market — the floor stayed and traded instead of going off, and the algorithm does the same." },
  { q:"When bullish and price consolidates into lunch, what is the plan?", o:["Wait for the lunch lows to be swept, then rally","Buy the consolidation high on the break","Exit everything before the lunch hour","Short the lunch lows for the afternoon"], a:0, e:"Mark the swing lows made during the lunch hour and wait for price to drop down and sweep them, then look for the rally afterwards." },
  { q:"Why was the older swing low ignored when framing the dealing range?", o:["Price held above the midnight open","It was outside the daily fair value gap","It formed before the 9:30 open","It had already been swept twice"], a:0, e:"Because the daily range is being traded and the midnight opening price is a factor — price went above it twice, so referring back to that older low is pointless." },
  { q:"What did the Nasdaq's lower low against the S&P's higher low indicate?", o:["Real accumulation, and a stop hunt below","Genuine weakness spreading to the S&P","That the correlation had permanently broken","A signal to sell both indices"], a:0, e:"SMT there showed the Nasdaq failing to go lower — under accumulation — making the S&P's push down just a stop hunt below a short-term low." },
  { q:"Where was the entry filled relative to the entry candle?", o:["A quarter point below its low","Exactly at its opening price","At the midpoint of its body","A quarter point above its high"], a:0, e:"\"I bought below that price 4110 and a half — I bought it at 4110 and a quarter\", buying the sell stops inside the fair value gap." },
  { q:"Why was half the position taken off at the marked rectangle?", o:["Old buy-side liquidity sat there, he could be wrong","It was the pre-set full profit target","The stop had already been hit once","Margin required reducing the size"], a:0, e:"That area was old buy-side liquidity and an imbalance that could stall it or make it a failure swing — \"I'm taking off half in the event that I'm possibly wrong.\"" },
  { q:"What happens if price returns into the fair value gap after leaving it?", o:["He is wrong and kills the trade","He adds to the position there","He moves the stop lower to allow it","He waits for a third test"], a:0, e:"Once it has done that once, it should never come back down again; if it does, \"I'm wrong… I'm going to kill the trade and move to the sidelines.\"" },
  { q:"He was wrong about 4070 and about the day's high target. What was the takeaway?", o:["The middle of the move is enough","Targets should be avoided entirely","Public calls should never be made","Both errors cancelled the day's profit"], a:0, e:"\"I was able to trade and take the lion's portion of the move in the middle. That's all you need\" — you don't need the absolute high and low." }
]
