[
  { q:"When he points at the May 16th low while price is far above it, what does that mean?", o:["It is the liquidity price is aiming for","It is a floor price should not break","It marks where he has already entered","It is where the daily bias flips bullish"], a:0, e:"\"My style is we're aiming for liquidity\" — drawing attention down to that low means it is the target, not a level expected to hold." },
  { q:"What is the scout and sniper analogy describing?", o:["He shows where to aim; you take the shot","He enters first and students copy the fill","Two traders splitting one position's risk","Scanning many markets before choosing one"], a:0, e:"\"I'm acting like a scout; you're the sniper in training\" — he points to where you should be aiming, and you do the work of scoping it up, pulling the trigger and managing it." },
  { q:"Why are the examples in index futures rather than forex?", o:["That is where the volatility currently is","Forex spreads are too wide for the model","The model does not translate to currencies","Index futures have no news releases"], a:0, e:"Price is price; index futures are pushed because that is where the volatility is right now, and he expects currencies to start moving wildly again within the next 12 months or so — at which point futures will look slow by comparison." },
  { q:"What does he say to students who only watch for the opening setup?", o:["Use a gap to get involved with the later move","Wait for the next day's open instead","Reduce size and take the opening trade anyway","Trade the London open in place of New York"], a:0, e:"If you don't get a trade at the opening, you can still use a fair value gap — you have to get involved with the move if it is going to travel to the target, which is exactly what he did that day." },
  { q:"What triggered the short entry on the five-minute chart?", o:["A swing high closing inside the gap","A close below the previous day's low","The order block being formed in real time","The 15-minute candle closing bearish"], a:0, e:"Three candles formed a swing high in the five-minute fair value gap; as soon as that candle closed he entered short, trusting that price had already gone through the gap and the move was bearish." },
  { q:"Which candle is identified as the bearish order block?", o:["The up-close candle right before the drop","The largest down-close candle of the day","The candle that closes the lunch consolidation","The candle whose wick reaches the May 16 low"], a:0, e:"On the 15-minute, the up-close candle immediately before price started going lower is the bearish order block; drawn forward in time, price returns and hits it." },
  { q:"Why was the stop moved once the trade ran in his favour?", o:["Volatility was high and he wanted no give-back","The broker required a trailing stop by rule","To free margin for a second entry","Because the target had already been reached"], a:0, e:"He moved it only because volatility was so high and he didn't want price coming back to knock him out — \"that's not fear, that's just sound money management.\"" },
  { q:"What warning opens the episode?", o:["He never DMs or asks for money — those are scams","He is closing the free YouTube mentorship","Index futures are unsuitable for small accounts","The May 16 low has already been invalidated"], a:0, e:"He does not use WhatsApp, will never direct message you on YouTube or Twitter and will never ask for money — accounts doing so are scammers impersonating him, and should be reported and ignored." }
]
