[
  { q:"When he points at the May 16th low while price is far above it, what does that mean?", o:["It is the liquidity price is aiming for","It is a floor price should not break","It marks where he has already entered","It is where the daily bias flips bullish"], a:0, e:"\"My style is we're aiming for liquidity\" — drawing attention down to that low means it is the target, not a level expected to hold." },
  { q:"What is the scout and sniper analogy describing?", o:["He shows where to aim; you take the shot","He enters first and students copy the fill","Two traders splitting one position's risk","Scanning many markets before choosing one"], a:0, e:"\"I'm acting like a scout; you're the sniper in training\" — he points to where you should be aiming, and you do the work of scoping it up, pulling the trigger and managing it." },
  { q:"You missed the setup at the open. What then?", o:["Use a fair value gap in the move","Wait for tomorrow's open instead","Take any breakout that appears","Trade a smaller size at random"], a:0, e:"Some students fixate on only looking for the setup at the opening. If you don't get a trade at the open, you can still use a fair value gap — you have to get involved with the move if it is going to travel down to the draw." },
  { q:"Why are the examples index futures rather than forex?", o:["It is where the volatility is right now","Index futures have the cheaper spreads","The model only works on index futures","Forex closes before the New York open"], a:0, e:"\"I'm pushing this asset class because this is where the volatility is — price is price, it doesn't make a difference.\" When forex starts moving big again, index futures will get slower and quieter by comparison; until then look for volatility where you can find it, and learn from it because it works the same way in forex." },
  { q:"What triggered the short entry on the five-minute chart?", o:["A swing high closing inside the gap","A close below the previous day's low","The order block being formed in real time","The 15-minute candle closing bearish"], a:0, e:"Three candles formed a swing high in the five-minute fair value gap; as soon as that candle closed he entered short, trusting that price had already gone through the gap and the move was bearish." },
  { q:"Which candle is identified as the bearish order block?", o:["The up-close candle right before the drop","The largest down-close candle of the day","The candle that closes the lunch consolidation","The candle whose wick reaches the May 16 low"], a:0, e:"On the 15-minute, the up-close candle immediately before price started going lower is the bearish order block; drawn forward in time, price returns and hits it." },
  { q:"Why was the stop moved once the trade ran in his favour?", o:["Volatility was high and he wanted no give-back","The broker required a trailing stop by rule","To free margin for a second entry","Because the target had already been reached"], a:0, e:"He moved it only because volatility was so high and he didn't want price coming back to knock him out — \"that's not fear, that's just sound money management.\"" },
  { q:"Which sequence repeats all the way down the day?", o:["Break, consolidate, break again","Gap up, fade, then gap down","Rally, reverse, rally, reverse","Trend, news spike, then chop"], a:0, e:"From the entry onward the day repeats one shape: break lower, consolidation, trade lower, a consolidation that bumps into stops, then sell-off — 'it's almost like it knows what it wants to do.'" }
]
