[
  { q:"What does he say about the day before the Fed chair speaks?", o:["It is usually a quiet, small-range day","It carries the widest range of the week","It reliably reverses the weekly trend","It should be traded only in the London session"], a:0, e:"With retail sales at 8:30 and the Fed chairman at 2:00pm the next day, the market was lethargic — the day before Fed chair Powell speaks is usually very quiet and low-volatility." },
  { q:"Why did the 9:30 decline not qualify as a short?", o:["Its gap was not above 50% of the displacement leg","The London session had not yet closed","It formed before the 8:30 news embargo lifted","The gap had already been rebalanced twice"], a:0, e:"The displacement leg would require a fair value gap above 50% of that leg's high and low, and there wasn't one — so nothing there fit the model for a short, and the bias was bullish anyway." },
  { q:"What was the divergence between the S&amp;P and Nasdaq that day?", o:["Nasdaq made a lower low, the S&amp;P refused to","Both indices made matching lower lows","The S&amp;P gapped while the Nasdaq did not","Nasdaq rallied while the S&amp;P sold off hard"], a:0, e:"Nasdaq made a lower low than its 10 o'clock low while the S&amp;P refused to go below the low it made at 10 o'clock — the divergence he calls SMT, read from inter-market relationships and no indicators." },
  { q:"Which market did he end up trading, and why?", o:["The S&amp;P — it was the one resisting lower prices","The Nasdaq — it had the relative equal highs","Both equally, to hedge the correlation risk","Neither — he stood aside ahead of the Fed"], a:0, e:"Every execution was in the S&amp;P and there were none at all in Nasdaq, even though he originally went in looking for a Nasdaq trade: the S&amp;P was the stronger market by the SMT read." },
  { q:"What is a close-proximity entry?", o:["Getting in near the gap when the ideal fill is missed","Placing the stop within a tick of the entry","Entering only on the candle that creates the gap","Adding contracts at the same price repeatedly"], a:0, e:"If you fumble the order or miss the ideal entry, getting in really close to the fair value gap is acceptable — provided price has not run too far away from it. That move gave eight candles of such opportunity." },
  { q:"What is the instruction for the day the Fed chair speaks?", o:["Do not try to trade it at all","Trade only the first ten minutes","Double the size for volatility","Trade it exactly like any day"], a:0, e:"\"Tomorrow's going to be very volatile. Be careful, do not try to trade tomorrow — you'll probably hurt yourself if you do. Or don't listen to me and learn the lesson the hard way.\"" },
  { q:"What signalled that market structure had shifted bullish a second time?", o:["The highs above being taken out","A close above the previous daily high","The Nasdaq catching up to the S&amp;P's low","The 2:00pm Fed speech being cancelled"], a:0, e:"As the market rallied, the highs being taken out gave one more indication that structure had shifted bullish again — and the add was made into the small fair value gap that formed off that move." }
]
