[
  {q:"What are the three stages of this mentorship?",o:["Yearner, learner, earner","Novice, trader, investor","Student, analyst, broker","Beginner, scalper, swing"],a:0,e:"Everyone starts as a green horn yearning to learn. The intent is to take yearners through becoming structured learners, and then — at your own discretion and timing — an earner."},
  {q:"What must you be precise about?",o:["The directional bias","The exact entry price","The contract expiry","The lot size you use"],a:0,e:"You don't need to be highly precise about your entries — he teaches forgiving entries — but you do need to be precise about the directional bias and where price is reaching for."},
  {q:"Why was the model stripped down for this mentorship?",o:["Excess content creates paralysis","Advanced concepts stopped working","YouTube limits the video length","Regulators banned the old model"],a:0,e:"The highest form of analysis creates exceptional traders, but the majority of students get bogged down in all of the content and it just creates analysis paralysis."},
  {q:"On the E-mini S&P, what is one tick worth?",o:["$12.50 — four to a handle","$50.00 — four to a handle","$5.00 — ten to a handle","$25.00 — two to a handle"],a:0,e:"A handle is four ticks — 4567 to 4568 — and a handle is $50 in the E-mini S&P, so every one tick is twelve dollars and fifty cents."},
  {q:"Why did ICT avoid MT4 for showing live results?",o:["It can be gamed to fake results","It cannot chart futures markets","It has no live order entry tool","It was shut down by regulators"],a:0,e:"It has been shown how frauds and fakes can use that platform to go in and edit their trades after the market has already moved, pretending they were profitable."},
  {q:"What weekly objective does he frame as enough?",o:["Around 25 handles a week","Around 25 handles a day","Around 250 handles a week","Around 5 handles a month"],a:0,e:"If you can take 25 handles out of a market like the E-mini S&P you can do very very well — it's a hypothetical income-based strategy, and you don't need to hit home runs."},
  {q:"What will he NOT be providing on the channel?",o:["Trade setups to take live","Assignments and PDF files","Charts drawn on beforehand","Lessons on a set schedule"],a:0,e:"Setups will not be given for trades. He draws attention beforehand to where price will likely draw to next so you can study it — not as an enticement to take a live trade."}
]
