[
  { q:"What is displacement, as defined here?", o:["An energetic move away from the gap and the level taken out","Any candle that closes outside the killzone window","A gap that forms on three consecutive candles","A run that stops exactly at relative equal highs"], a:0, e:"\"It hasn't really shown me what displacement is — something energetic where it moves away from that fair value gap.\" It has to move away from the gap and away from the low or high it just took out." },
  { q:"Why was the nearer short-term low rejected as the setup?", o:["The next candle opened right at that low","It sat above the previous week's high","It formed outside the London killzone","Its gap was on the 15-minute chart"], a:0, e:"The fair value gap formed on that candle and the very next candle opened essentially right at that low, so price had not moved away — there was no displacement." },
  { q:"When is the London open killzone in forex?", o:["2:00am to 5:00am New York time","7:00am to 10:00am New York time","8:30am to 11:00am New York time","Midnight to 3:00am New York time"], a:0, e:"\"It's two o'clock in the morning to five o'clock in the morning, New York local time — that's the kill zone for London open.\" Set the chart's time window to New York." },
  { q:"What does the market do with relative equal highs?", o:["Runs through them at a later point","Uses them as durable resistance","Leaves them as an efficient boundary","Rebalances the gap beneath them first"], a:0, e:"\"The market does not like to leave that — that is not efficient.\" It's only efficient for retail technical analysis, which reads the clean line as resistance." },
  { q:"Why is the dollar index used when trading euro?", o:["It is the barometer for an inverted market","It shares euro's killzone timings exactly","It prints cleaner fair value gaps","It sets the euro's daily opening price"], a:0, e:"Euro is the trading market, so you need something to measure its movement with — the intermarket relationship. Dollar and euro are inverted, so a dollar buy level is a euro sell moment." },
  { q:"How should risk per trade be expressed while learning?", o:["A fixed percentage of account equity","A round dollar figure per trade","A fixed pip distance on the stop","One lot for every open setup"], a:0, e:"Take the money in the account times one percent as the maximum — \"preferably you should be doing a half a one percent or maybe a quarter of one percent\" while learning." },
  { q:"What happens if price misses your gap on the first attempt?", o:["Wait, because the killzone is still open","Chase it with a market order","Move the limit down to the deeper low","Cancel and stand down for the day"], a:0, e:"\"We wait, we don't chase it, we don't go in here thinking oh well I missed the move — we still have time, the kill zone for London open is still open.\" It retraced into the fill." }
]
