[
  { q:"How is the Sunday opening gap used through the rest of the week?", o:["Plotted across the week as a dynamic level","Deleted once Monday's range is formed","Used only as the weekly profit target","Averaged with the weekly open for a midpoint"], a:0, e:"Put the Sunday gap opening on the chart and extend it through the entire week — there is often a lot of valuation around it, so it gets treated as a dynamic price level." },
  { q:"If price is trading below the Sunday opening gap, what is expected of that level?", o:["It should act as resistance","It should act as support","It becomes irrelevant until Friday","It flips to the weekly equilibrium"], a:0, e:"Above it, look for it to act as support; below it, look for it to act as resistance. The day shown did exactly that on the way back up." },
  { q:"Which week is the Sunday gap said to matter most in?", o:["A consolidation week such as FOMC","A week with a clean one-way trend","Any week that opens with no gap","The final week of the quarter"], a:0, e:"Sometimes the week just runs away from it. It earns its keep in weeks where there's consolidation, like an FOMC week, which creates the choppy range-bound conditions." },
  { q:"To hunt a long, which price leg is the dealing range fib anchored to?", o:["The impulsive up swing, low to high","The prior down swing, high to low","The whole session range, open to close","The overnight range, midnight to open"], a:0, e:"Anchor on the expansion swing that runs in the direction you want to trade — for a long, from that low up to that high, then wait for the retracement." },
  { q:"Where does the long get hunted once the fib is drawn?", o:["At or below 50% — in the discount","Anywhere above the 50% level","Exactly at the swing high","At the 100% extension beyond the high"], a:0, e:"The retracement down to and below 50% is the discount, and that is where the long is hunted — better still if it lands in a fair value gap." },
  { q:"What does calling the morning session \"sloppy\" mean here?", o:["Few entry mechanics to work with","The session lost money outright","The data feed printed bad candles","Volume was too low to fill orders"], a:0, e:"Sloppy means it isn't giving you a whole lot to work with — very few options, and you must know exactly what you're looking for. It was a nice delivery without the mechanics of entry." },
  { q:"Do you need the exact level he pointed out?", o:["No — the equal highs are enough","Yes, or the trade is invalid","Only when trading the afternoon","Only if a gap sits above it"], a:0, e:"If price is going to trade down into the Sunday gap opening, look for it to run to the relative equal highs — 'you don't need to have this level that I pointed out, this is enough.' Relative equal highs are the buy-side pool; the specific level is a refinement, not the requirement." }
]
