[
  { q:"What does a rising dollar index signal?", o:["Risk off — a flight to quality","Risk on — money rotating into equities","A pause before foreign currencies rally","A seasonal low forming in the indices"], a:0, e:"A rising dollar is a risk off scenario: other asset classes generally decline and the dollar is treated as a flight to quality or safe haven, so money pours in while it pours out of risk assets." },
  { q:"What does the 8:30am opening price refer to?", o:["The New York session open, 8:30 to 11:00","The midnight New York candle's open","The London killzone open at 2:00am","The equity market open at 9:30"], a:0, e:"\"The New York session is the 8:30 to 11 time period, New York local time\" — not to be confused with the New York midnight candle's opening price." },
  { q:"You are bearish and price rallies above neither opening price. What does that tell you?", o:["It is extremely bearish","The bias has been invalidated","A Judas swing is still pending","Power of Three has been cancelled"], a:0, e:"It cannot even rally to a short-term premium above the opening price at key levels and times — extremely heavy. So it will not give the clean short-term rallies to fade." },
  { q:"How do you participate when the market is too heavy to rally?", o:["Use small imbalances to join what is in motion","Wait for the 8:30 Judas swing anyway","Buy the oversold reading and scale in","Widen the stop and hold overnight"], a:0, e:"Drop to the 2-minute and 1-minute charts and use the small pockets of imbalance to get in sync with the move already underway, leaving out the element of a rally above the 8:30 opening price." },
  { q:"With two fair value gaps stacked, which one is the entry?", o:["The lower gap, with the upper one as risk","The upper gap, for the better price","Whichever formed first in time","Neither — wait for a third to form"], a:0, e:"\"If you have two fair value gaps you're using this as the entry and you're using this as the risk\" — the lower gap fills you, and the stop must allow for a trade up into the upper one." },
  { q:"Which level of a bearish order block is least likely to be traded to?", o:["The high of the order block","The low of the order block","The open of the order block","The mean threshold halfway"], a:0, e:"He works with the low, the open and the mean threshold, and treats the high as the level least likely to be reached — and price never got to it in this example." },
  { q:"When should you move a stop loss to a nearer level?", o:["Once time and price are behind you","As soon as price makes a new low","At the 9:30 equity market open","Whenever the trade shows any profit"], a:0, e:"\"Just because it goes down lower, it doesn't mean jam your stop loss to here… you need to have time and price behind you before you start moving your stop loss.\"" },
  { q:"How long is a typical trade held?", o:["Ninety minutes to two hours","A full 24-hour session","Several days, exiting on strength","Into the following Monday open"], a:0, e:"He is 100% in a session or a day and out before the close — no overnight and no weekend holds — with the typical position lasting 90 minutes to two hours maximum." }
]
