[
  { q:"Which hour of the day is a flat no-trade period?",
    o:["Noon to 1:00 pm New York time",
       "8:30 to 9:30 am New York time",
       "11:00 am to noon New York time",
       "3:00 to 4:00 pm New York time"],
    a:0,
    e:"New York lunch, noon to 1:00 pm, is a no-trade time period — \"don't trade during that time, not even in demo\". It can do weird things or go sideways, and it is not a clean time of day for price action." },

  { q:"How is a swing high defined here?",
    o:["A candle with a lower high either side of it",
       "An up-closed candle above the previous session",
       "The highest close of the last twenty candles",
       "Any high that stops two ticks under an old high"],
    a:0,
    e:"A swing high is a candle with a lower high to the left of it and a lower high to the right of it — a three-candle pattern. It does not matter whether the candles close up or down; the swing point is simply where liquidity is placed." },

  { q:"What does the elephant-in-the-paddling-pool analogy describe?",
    o:["Displacement — an obvious, energetic move",
       "The volume needed to confirm a breakout",
       "How a large order fills across the book",
       "The size a position should be scaled to"],
    a:0,
    e:"When price goes above an old high and trades back down below it, you want to see obvious displacement — energetic and animated, like an elephant falling into a filled children's pool. A lethargic, anemic run lower is not enough to act on." },

  { q:"Three drives run up into an old high. What follows?",
    o:["The third drive need not clear the old high",
       "The third drive must close above the old high",
       "The setup is void until a fourth drive forms",
       "The old high should be redrawn at each drive"],
    a:0,
    e:"You don't have to see that third high take out the old high. Each swing high already builds liquidity — bears sell it and place buy stops above the previous high, which keep getting taken — so the liquidity is being run out along the way." },

  { q:"What is 'spooling' in a buy program?",
    o:["The algorithm continuously offering higher prices",
       "Large buy orders queuing up at the exchange",
       "Volume building steadily before a breakout",
       "Stops trailing upward behind a rising price"],
    a:0,
    e:"A small stop hunt below a swing low can start a buy program, where the algorithms spool — continuously offering higher prices. It does not matter what the volume is; the mismatch between price and volume is the signature of manipulation." },

  { q:"After 1:30 pm, which two setups are you looking for?",
    o:["A swing low violated, or displacement then a gap",
       "A breakout retest, or a moving-average crossover",
       "An order block tap, or a breaker block rejection",
       "An opening-range break, or a volume-profile edge"],
    a:0,
    e:"Wait for a swing low to be violated and buy those sell stops, or — if no swing low trades below — wait for a sudden displacement higher and buy the retrace into the fair value gap. \"That's the only two patterns you need\"; no breakers, no order blocks." },

  { q:"Which contract month should you be trading into rollover?",
    o:["Whichever has the larger open interest",
       "Always the nearest expiring front month",
       "Whichever posted the higher daily volume",
       "The next month out, from the first of the month"],
    a:0,
    e:"Around the first or second day of the week before expiration — the third Friday of the delivery month — monitor open interest and trade the month with the larger number, because you want the liquidity in the most-traded contract month." }
]
