[
  { q:"Price broke below the old high but left no fair value gap. What then?",
    o:["Nothing — the setup does not meet the criteria",
       "Short it anyway, the structure break is enough",
       "Drop to a lower timeframe until a gap appears",
       "Wait for the gap to fill and then buy the low"],
    a:0,
    e:"In the S&P example price broke down below the old high but did not create a fair value gap, so there was nothing to do. The Nasdaq example repeats it: the relative equal highs were taken but no gap followed, so it did not even meet the criteria." },

  { q:"What does 8:30 in the morning represent in this lesson?",
    o:["The start of the hunt for an old high or low",
       "The moment the overnight range is finalised",
       "The last chance to close an Asian-session trade",
       "The point where the fib should be redrawn daily"],
    a:0,
    e:"\"8:30 in the morning starts the hunt — basically that's what 8:30 in the morning is to me.\" You are looking for an old high (or low) to be violated at that time, then for the model to form." },

  { q:"With the fib on the range, where do you look for a target?",
    o:["A low or an imbalance below the 50% level",
       "The first old high sitting above equilibrium",
       "The exact midpoint of the range every time",
       "Whichever level the previous day closed at"],
    a:0,
    e:"After dropping the fib on the low-to-high range, you look for a low or an imbalance below the equilibrium price point. In the S&P example there was a swing low and an imbalance beneath it, and price drew down into both." },

  { q:"Which timeframe do you start with before working down?",
    o:["The 5-minute chart",
       "The 1-minute chart",
       "The hourly chart",
       "The daily chart"],
    a:0,
    e:"On the Nasdaq example for Thursday 27 January: \"this is a 5 minute chart, this is the time frame you start with and you work down.\"" },

  { q:"Which three things should each journalled example record?",
    o:["Time to the gap, time to target, drawdown taken",
       "Volume, open interest and the closing spread",
       "Session name, contract month and tick value",
       "News released, sentiment and the VIX reading"],
    a:0,
    e:"Log how long it took from the market structure shift to price getting up into the fair value gap, how long from entry down to your target, and how much heat or drawdown you would have weathered." },

  { q:"Why frame the trade as the total range available in hindsight?",
    o:["It builds a framework for recognising recurring setups",
       "It guarantees the entry and exit can both be filled",
       "It makes the results look better in a study journal",
       "It removes the need to check lower timeframes later"],
    a:0,
    e:"The total range is shown because it gives a framework for how these examples look. They are never exact photocopies of previous instances, but the recurring similarities are what train your eye — the deer-track analogy." }
]
