[
  { q:"What had already printed before he took the long?", o:["A market structure shift to the upside","A bearish engulfing candle on the hourly","A double bottom at the session low","A moving average crossover signal"], a:0, e:"He opens with \"we had a market structure shift to the upside — I'm looking for a gap fill from Friday's close.\"" },
  { q:"How did he get into the position?", o:["A limit order down in the fair value gap","A market order at the current price","A stop order above the session high","A trailing entry once it broke out"], a:0, e:"He placed a limit entry and waited for price to \"drop down into that fair value gap\" rather than buying where price already was. It filled on the low candle." },
  { q:"While the trade was open, what did he say he was watching?", o:["The candles, not the profit number","The floating P/L under the position","The volume histogram at each level","The tick chart for order flow prints"], a:0, e:"\"I'm not watching the number underneath that profit — that's not what I'm watching, I'm watching the candles.\" The question is whether price keeps moving toward the objective." },
  { q:"What did he expect price to do around the 14,120–14,140 area?", o:["Consolidate and reaccumulate for new longs","Reverse hard and fill the gap downward","Accelerate straight through without pausing","Stall out and end the session flat"], a:0, e:"He anticipated a pause there — consolidation and reaccumulation for new longs, \"kind of like a bull flag\" — rather than a straight run to target." },
  { q:"Why did he expect price to trade above 14,160?", o:["Retail sells resistance, so stops sit above it","The level had never been tested before","Volume had dried up at that price","A moving average was converging there"], a:0, e:"Retail resistance thinking says \"it went down from there the last time, so I'll get short.\" He expected price to \"swat bust through the door\" and run into 14,180 instead." },
  { q:"What was his plan once price ran above his level?", o:["Take six off to fund it, stops to even","Close the whole position immediately","Add six more contracts to press the move","Reverse and go short into the order block"], a:0, e:"\"If it runs there I'll take six off to fund the position, roll the stops to even, and then see if I can get that limit order at fourteen thousand two twenty.\"" },
  { q:"Why did he pull up the E-mini S&P micro mid-trade?", o:["To see if the correlated market agreed","To hedge the NASDAQ position with a short","To compare tick sizes before scaling in","To check whether the session had closed"], a:0, e:"He looked at it \"just to get a feel\" — it looked like it wanted to run as high as well, which \"gives me fuel or confidence that this is going to run up into that level.\"" }
]
