[
  { q:"What is an outside day?", o:["Higher than yesterday's high, lower than its low","Any day that closes outside the opening range","A day whose whole range sits above yesterday's","A session that trades only after the equities close"], a:0, e:"An outside day trades higher than the previous day's high and lower than the previous day's low, so its entire range lies outside yesterday's — and this one closed down." },
  { q:"What tends to follow when price trades down to an old low but stops short of it?", o:["A choppy day, especially after an outside day","An immediate expansion through the low","A gap open in the opposite direction","A trending day with no retracements"], a:0, e:"Falling short of the old low is what people read as a double bottom and it feels safe; it tends to produce a choppy day, particularly after an outside day with a down close. Here price stopped at 3856, one handle above the 3855 low." },
  { q:"When does he say probability genuinely becomes 50/50?", o:["When price trades back into the middle of the range","At every session open before the first hour","Whenever an imbalance has been rebalanced","On any day with scheduled economic news"], a:0, e:"Anybody can claim a 50/50 expectation, but it statistically moves to 50/50 when you start trading back into the middle of the range — which is where the day's listless chop took place." },
  { q:"What defines a consolidation day?", o:["An initial range held until three in the afternoon","A day that closes within one tick of its open","A range narrower than the previous three days","A session where no fair value gaps form at all"], a:0, e:"The market creates an initial range and stays in it until three o'clock in the afternoon — formerly driven by the bond close, now by the three to four o'clock window when equities close and on-close orders set the tone." },
  { q:"What did he tell people to mark on their charts in advance?", o:["Vertical lines at 3:00 and 4:00 New York time","The previous week's high and low","Every fair value gap on the four-hour chart","The London open and the Asian session high"], a:0, e:"He told everyone on Twitter to add vertical lines at three and four o'clock New York local time — that window was where the day's real setup would form — and to study the middle of the daily range." },
  { q:"What happens to the buy stops sitting above the relative equal highs?", o:["They become a wave of willing buyers at market","They are cancelled once the range is confirmed","They are filled gradually through the lunch hour","They push price up to the next daily objective"], a:0, e:"Those buy orders are protective stops on short positions; when price trades above them they become a rushing liquidity wave of willing buyers at the market — exactly what is needed to sell into at the close." },
  { q:"How is the target midpoint of the day calculated?", o:["Splitting the day's high and low in the middle","Averaging the open and the previous close","Taking 50% of the previous day's range","Using the midpoint of the lunch consolidation"], a:0, e:"Take the low of the day and the high of the day from around 9:30 and split it in the middle — that midpoint is where the market wants to gravitate back to on a consolidation day." },
  { q:"Where did he take the first scale on the short from 3940.75?", o:["3908.75 — the middle of the day's range","3855 — the untraded old daily low","3933.25 — the relative equal highs","3856 — one handle above the old low"], a:0, e:"Four contracts came off at 3908.75, the middle of the range, with the rest left running against a limit order down at 3855 — the level his longer-term bias still favoured." },
  { q:"What is his objection to trading from indicators?", o:["They give numbers, not logic and narrative","They repaint too often to be reliable","They are unavailable on futures platforms","They only work outside the killzones"], a:0, e:"\"They don't give you logic and narrative, they just give you a crunching of the numbers\" — that is beating up the data of price action rather than reading and understanding the tape." }
]
