[
  { q:"At the 9:30 open, why does he expect the swing low below the fair value gap to be taken out?", o:["Traders buying the gap park stops below it","The gap is invalid until the low is broken","Exchanges widen spreads at the opening bell","Overnight volume always exits at the low"], a:0, e:"He expects people to see the gap, buy immediately, and place their stop below that swing low — those sell stops (at 13,612) are the target, and taking them does not negate the gap." },
  { q:"Where does he actually take the long entry?", o:["Back inside the original fair value gap","At the swing low as it is being swept","At the opening print of the 9:30 candle","Above the swing high on the breakout"], a:0, e:"After price sweeps the low, he buys as it trades back up into that same fair value gap — the low sits outside and below the gap, so the gap is still valid." },
  { q:"Why does he wait for the candle to close before treating the gap as set?", o:["The close is what completes the imbalance","The close resets the daily opening price","Closed candles carry more volume weight","The platform only draws gaps on closes"], a:0, e:"\"I'm watching this candle, see how it closes, because that will complete our imbalance.\"" },
  { q:"What does he say about using a stop loss when trading the open like this?", o:["He normally uses one, but here manages by hand","Stops should never be used on any trade","A wide stop below the session low is required","Only a hard stop at entry is acceptable"], a:0, e:"He generally likes trading with a stop, but at the open \"stops can be taken really easily and then reverse and never give you a chance to be in it.\" He is explicit he is not encouraging trading without one — he sits ready to close at market." },
  { q:"Why was the 80 level chosen as the objective?", o:["A fair value gap sits there in premium","It was the highest price of the prior week","It matched a round-number psychological level","It was where his stop loss would break even"], a:0, e:"There is a fair value gap at the 680 level and it is above equilibrium — a premium market — plus it is around 50 handles, roughly $1,000, and it takes the account to the $50,000 mark." },
  { q:"What is his rule for trading an FOMC day?", o:["Trade the morning, but be done early","Avoid the session entirely from open to close","Trade only after the announcement lands","Double the position to cover the volatility"], a:0, e:"\"At FOMC you can trade in the morning but you got to be done early.\" He also stresses being aware of the economic calendar because of the volatility later in the day." },
  { q:"Why does he take a smaller objective than he believes is available?", o:["He is on vacation and wants it closed","The market was in a discount below equilibrium","Commissions would eat a larger target","His broker limited the position size"], a:0, e:"\"I do believe it's going to go higher, but I'm on vacation, so I want to kind of like let me take this long entry\" — the objective is sized to the circumstances." }
]
