[
  { q:"On a bearish day, how is the opening range constructed?", o:["Open to the high, projected below the open","Open to the low, projected above the open","The high to the low of the previous session","The first fifteen minutes after the 9:30 bell"], a:0, e:"The day opens and rallies, and that rally is the Judas swing. Take the range from the opening price to that high and project it below the opening price." },
  { q:"What does he say lives inside the opening range?", o:["Every premium array and shorting candidate","Only the very first fair value gap of the day","Nothing tradeable, so it is a no-trade zone","The distribution phase and the closing price"], a:0, e:"Every premium array he teaches, in any approach including the paid mentorship, will reside and form in the range between the open and its high projected down." },
  { q:"What is the whole of daily bias, reduced to one question?", o:["Will the range expand above or below the open?","Where will the daily candle close, to the tick?","Which session will print the day's largest range?","Is today's volume above the twenty-day average?"], a:0, e:"Take the close out of it. You do not need to predict the closing price to be profitable. You only need to know whether the daily range is more likely to expand higher or lower than the opening price." },
  { q:"How many candles are needed to define a swing low?", o:["Three, a low with a higher low on each side","Five, so the pattern is properly confirmed","Two, a down close followed by an up close","Seven, matching the Williams fractal setting"], a:0, e:"Three candles make a swing low. He is dismissive of the Williams fractal for this: it is way too many candles and you have already missed the move." },
  { q:"Where does the stop go when trading a bearish breaker?", o:["Just above the breaker candle itself","Above the higher fair value gap in the leg","At the midnight New York opening price","Above the high of the previous trading day"], a:0, e:"The foundation of the ICT breaker is that the market should mostly stay in the lower half of the breaker candle, so the stop sits just above that candle, not far above it." },
  { q:"In the top-down search, when do you stop dropping timeframes?", o:["At the first fair value gap you come to","At the one minute chart, checking them all","When two gaps appear on the same timeframe","Once the candles look beefy and prominent"], a:0, e:"He strips 5, 4, 3, 2 then 1 minute and takes the first gap found. Find one on the four and you never go to the three. Find none at all, even on the one minute, and you do not have a trade." },
  { q:"What does it mean when the exchange raises margin requirements?", o:["Big moves are coming; it is not coincidence","Volatility has just finished and will now fall","Retail participation in that contract is rising","The contract is about to roll to a new month"], a:0, e:"He flags this explicitly for your notes: raising the margins is the exchange tipping their hand that huge moves are coming." },
  { q:"Why does price tend to return over a long, drawn-out candle?", o:["It left porous prices that were never offered well","Exchanges require every candle to be retested","Long candles are always errors in the data feed","Stops sit at the exact midpoint of such candles"], a:0, e:"The paint roller analogy: one pass leaves porous places where the market was not efficiently offered, so an efficient market goes back and applies the paint evenly over that range." },
  { q:"Why does he take 8:30 as the crosshairs time for the indices?", o:["The news embargo lifts and events arrive at once","It is the official opening bell for stock indices","London traders close their books at that moment","Daily margin requirements are recalculated then"], a:0, e:"The news embargo lifts at 8:30 and typically a bunch of news events are ushered into the marketplace at that time, which may act as a smokescreen or a catalyst." }
]
