[
  { q:"After price runs a level of relative equal highs, what must happen next for a setup to exist?", o:["A short-term low taken out with displacement","Any close back below the relative equal highs","A retest of the highs on a lower timeframe","A second run through the same highs"], a:0, e:"\"It's not that it goes above the relative equal high and then goes down below that — that's not it.\" You must see it take out a short-term low with an energetic displacement move; until then there is no setup." },
  { q:"Once the displacement leg exists, where is the entry taken?", o:["In the fair value gap inside that leg","At the extreme high of the run on the highs","At the short-term low that acted as the trigger","At the midpoint of the whole day's range"], a:0, e:"The displacement leg is the foundation of the setup; once you have it, you go back into that area and look for the fair value gap." },
  { q:"In the second entry pattern, how do you treat an old fair value gap above the market?", o:["Use its low exactly like a relative equal high","Require a full close of the gap before acting","Ignore it until the daily candle closes inside","Enter blind at its upper edge with a tight stop"], a:0, e:"It doesn't have to completely close the gap — use the low of the fair value gap and apply the same logic used for relative equal highs, then look for the trigger and displacement." },
  { q:"Why does he present the day where nothing formed as a good lesson?", o:["Valid logic keeps you out of bad trades","It shows the model needs a new filter added","It proves news days always invalidate the model","It shows entries work better after 1:30pm"], a:0, e:"Sound logic behind a model should prevent you from taking bad trades; no entry pattern formed, so no losing trade happened — that is evidence of validity, not that the model broke." },
  { q:"What stage does he say the audience is at, and what should they be doing with the pattern?", o:["Back testing it in old charts, not trading it","Trading it live in a small funded account","Demo trading it every session without exception","Waiting until the mentorship series is finished"], a:0, e:"The mentorship is in its development stages — this is discovery, where you go back through the data in your old charts looking for the pattern, not trading and not even demo trading it yet." },
  { q:"What does he mean by the journal promise to \"endure\" losses?", o:["Losses come, but must not defeat you","Losses can be avoided with enough back testing","Every loss should be doubled down on next","Losses only matter once you are funded"], a:0, e:"\"Notice I said endure — you're not going to be defeated by those losses, you're just going to have to endure them,\" because trading is all about managing losing trades." },
  { q:"How does he classify missing a big move you were watching?", o:["A loss, with a mental impact you control","A neutral event with no bearing at all","Worse than a monetary loss in every case","Proof the model failed on that session"], a:0, e:"Missing moves is a loss, a monetary loss is a loss, and a losing demo trade is a loss — the mental impact is the part you have control over." }
]
