[
  { q:"Why did he trust the high above his short would break?", o:["The swing highs beside it were lower","Lower highs and lower lows had formed","An oscillator had turned over there","It was the highest price of the day"], a:0, e:"Not because of 'lower highs and lower lows' — because of the nesting of the highs: from the session high there was a swing high next to it and another beyond, making that an intermediate term high with the swing highs either side lower than it. He wanted to be short close to it, because it was likely to break." },
  { q:"What defines a swing high?", o:["A lower high candle on either side of it","Any high above the previous session's high","A high formed within the first hour of trade","The highest price printed in the dealing range"], a:0, e:"A swing high is a high with a lower high candle to the left of it and a lower high candle to the right of it — the one in the middle is your swing high." },
  { q:"Which opening price frames the whole daily range?", o:["Midnight New York","8:30 in the morning","1:30 in the afternoon","The 9:30 equity open"], a:0, e:"Two separate reference points: the midnight opening price for the entire daily range, and the 8:30 opening price when you are looking at the morning session." },
  { q:"You missed the first fill. Where is the second entry?", o:["The broken swing high candle's high","Below the old low, on the breakout","At the midnight opening price again","Wherever the next round number is"], a:0, e:"A swing high was broken to the upside and a low was taken out; if price touches that candle's high again you can be short there, using the same imbalance and fair value gap technique. Note what he is not doing: waiting for a breakout below the low." },
  { q:"Why is a down close candle after a run-up not automatically an order block?", o:["The imbalance is the real context, not the candle","Order blocks only form on the daily timeframe","Order blocks must always be up close candles","A candle needs three retests before it counts"], a:0, e:"He calls this out directly: people who don't understand order blocks buy any down close candle after a run-up and think it is a bullish order block. It is not — in this case the real context was the imbalance." },
  { q:"What does he do after a big winning move to stay out of trouble?", o:["Switch to a demo account for the next session","Double the size while the read is still hot","Close the platform for the rest of the week","Move the stop to breakeven and add contracts"], a:0, e:"After a big move, don't trade the morning session — he purposely goes into a demo account to appease the desire to trade, so a losing trade doesn't dampen the win." },
  { q:"What does he say happens if you keep pushing your edge?", o:["You dull it instead of sharpening it","You compound the account far faster","You finally learn where the real limits are","You qualify for lower exchange margins"], a:0, e:"You don't want to push your edge, because if you keep pushing it you dull it. You sharpen it by knowing when to get in and when to get out." },
  { q:"What did he want to see immediately after executing the short?", o:["Displacement away from his entry","A retest of the exact fill price","Volume rising on the up closes","A close above the 50% equilibrium"], a:0, e:"Displacement is what he was waiting for; when it occurs it is the confirmation, and you can sit back and let the trade do its thing." },
  { q:"Where is equilibrium inside a dealing range?", o:["At 50% of the high to the low","At the midnight opening price","At the middle of the fair value gap","At the last short term high formed"], a:0, e:"Measure the high to the low: 50% is equilibrium inside that dealing range, with premium above and discount below." }
]
