[
  { q:"How many halos marked an intermediate term high in the chart books?", o:["Two circles drawn above the swing","One circle, the same as any swing","Three circles, the maximum used","None; only lows were ever ringed"], a:0, e:"One halo was a short term high, two halos an intermediate term high, and three halos a long term swing high — a way of classifying the level of the high that is forming." },
  { q:"What defines a swing high?", o:["A lower high candle on either side of it","Any high above the previous session's high","A high formed within the first hour of trade","The highest price printed in the dealing range"], a:0, e:"A swing high is a high with a lower high candle to the left of it and a lower high candle to the right of it — the one in the middle is your swing high." },
  { q:"Which opening price frames the whole daily range?", o:["Midnight New York","8:30 in the morning","1:30 in the afternoon","The 9:30 equity open"], a:0, e:"Two separate reference points: the midnight opening price for the entire daily range, and the 8:30 opening price when you are looking at the morning session." },
  { q:"What was the entry trigger on the three-minute chart?", o:["Price bumping the top of the fair value gap","A close below the previous session's low","The moment displacement had already occurred","A moving average crossing under another one"], a:0, e:"At 10:33 price worked up inside the imbalance and, as it hit the top end of the fair value gap and started to move away, that was the short." },
  { q:"Why is a down close candle after a run-up not automatically an order block?", o:["The imbalance is the real context, not the candle","Order blocks only form on the daily timeframe","Order blocks must always be up close candles","A candle needs three retests before it counts"], a:0, e:"He calls this out directly: people who don't understand order blocks buy any down close candle after a run-up and think it is a bullish order block. It is not — in this case the real context was the imbalance." },
  { q:"What does he do after a big winning move to stay out of trouble?", o:["Switch to a demo account for the next session","Double the size while the read is still hot","Close the platform for the rest of the week","Move the stop to breakeven and add contracts"], a:0, e:"After a big move, don't trade the morning session — he purposely goes into a demo account to appease the desire to trade, so a losing trade doesn't dampen the win." },
  { q:"What does he say happens if you keep pushing your edge?", o:["You dull it instead of sharpening it","You compound the account far faster","You finally learn where the real limits are","You qualify for lower exchange margins"], a:0, e:"You don't want to push your edge, because if you keep pushing it you dull it. You sharpen it by knowing when to get in and when to get out." },
  { q:"What did he want to see immediately after executing the short?", o:["Displacement away from his entry","A retest of the exact fill price","Volume rising on the up closes","A close above the 50% equilibrium"], a:0, e:"Displacement is what he was waiting for; when it occurs it is the confirmation, and you can sit back and let the trade do its thing." },
  { q:"Where is equilibrium inside a dealing range?", o:["At 50% of the high to the low","At the midnight opening price","At the middle of the fair value gap","At the last short term high formed"], a:0, e:"Measure the high to the low: 50% is equilibrium inside that dealing range, with premium above and discount below." }
]
