[
  { q:"Does the draw on liquidity have to be reached for the setup to work?", o:["No — you participate in the expansion towards it","Yes — the target must trade or the model fails","Only if the draw sits above the daily opening","Only when the draw is more than 50 points away"], a:0, e:"\"The draw on liquidity does not need to be traded to to have a profitable framework or setup\" — you look for a setup that lets you participate in the expansion towards the level, like a magnet drawing price up." },
  { q:"Why were the relative equal lows below price not the buy level?", o:["They were not in a discount of the day's range","They had already been taken out that morning","They sat above the 12,553 objective","They formed outside the New York session"], a:0, e:"Sell side sat there, but it was not a discount from the day's low to high — the buy is inside the fair value gap because that is at or below equilibrium, the 50% of that range." },
  { q:"What time does he say the algorithm starts seeking liquidity that afternoon?", o:["1:30, after the lunch retracement from 12:10","9:30, at the equities open in New York","3:00, when positions get squared off","Midnight, when the new trading day begins"], a:0, e:"The high formed at 12:10 — lunch time, which usually creates a retracement or consolidation — then at 1:30 the algorithm starts seeking liquidity, seeking sell side if it is going to continue higher." },
  { q:"What reason is given for expecting a bullish counter-trend retracement?", o:["Traders square up before the weekend close","The weekly opening price was still untouched","A bullish divergence printed on the oscillator","The seasonal tendency turns bullish in June"], a:0, e:"The market had been down a long time and most people want out over the weekend, so the algorithm starts squeezing them to get their positions squared before the Friday close." },
  { q:"On which timeframe was the actual entry pattern found?", o:["The 2-minute — order block with the gap above","The 15-minute, at the 9:30 manipulation","The hourly, at the swept relative equal lows","The daily, at the 12,553 relative equal highs"], a:0, e:"The 4-minute showed only a small gap he wasn't interested in and the 3-minute one that would be fine; the 2-minute showed the down-close candles forming the order block with the fair value gap, and price traded into it." },
  { q:"What went wrong with the 20-contract exit?", o:["It filled at market instead of as a limit","The broker rejected it for insufficient margin","It filled at 12,553 far above the intention","It was placed on the wrong contract month"], a:0, e:"He wanted to take 20 off above 12,430 as a limit order but it ended up closing as a market order — blamed on working in TradingView rather than a live platform, and on placing it from a phone." },
  { q:"What does he recommend writing in the empty space on a back-tested chart?", o:["First-person commentary as if you saw it coming","The exact contract size you would have traded","A list of the indicators that confirmed the move","The news releases scheduled for that session"], a:0, e:"You write the narrative in your own words as though you expected it — the subconscious retains the image and the words, building pseudo-experience so that when you see it live your brain remembers having done it before." },
  { q:"What comparison does he use to explain why annotation works?", o:["The reticular activating system and buying a car","Muscle memory built by repeating a golf swing","Compound interest accumulating in an account","Learning a language by living in the country"], a:0, e:"He compares it to the reticular activating system: buy a car and suddenly everyone seems to have the same one, because it has become meaningful to you — charts take on that characteristic when you put your personality into them." },
  { q:"What limit does he place on the demo account he shows?", o:["It proves he understands it, not that you can","It proves the same returns are available live","It shows the minimum capital the model needs","It shows the model never has losing trades"], a:0, e:"\"Just because I'm doing it with a demo account doesn't mean that you're going to be able to go out there and do it too with a live account. The only thing I'm showing you here is I understand what I'm doing\" — and the account does contain two back-to-back losers." }
]
