[
  { q:"What are the three phases of Power of Three on a bullish day?", o:["Open near the low, dip lower, rally and close high","Open near the high, rally, then close near the low","Open at equilibrium, chop sideways, then gap away","Open on the high, dip, and close back at the open"], a:0, e:"If bullish, expect the opening price near the low of the day or session, then a trade lower making an important low, then a rally to the high and a close near it." },
  { q:"How do you find an order block?", o:["Consecutive down closes before a surge with a gap","The single largest volume candle of the session","Any candle whose wick touches the 50% of the range","The last candle before the New York opening bell"], a:0, e:"Consecutive down close candles right before a price surge that has an imbalance. High probability means the bias is bullish and the surge is real displacement." },
  { q:"There was a huge overnight run up on the NASDAQ. What do you do?", o:["Skip the morning; wait past 1:00 pm for lows taken","Buy the 8:30 open to join the move before it goes","Sell the open, since overnight runs always reverse","Trade normally, since the run has no bearing on it"], a:0, e:"If there is a big run overnight in equities, avoid the New York session entirely, wait until the other side of lunch at 1:00 pm New York time, and anticipate the lunch or morning session lows being taken out." },
  { q:"Price wicks below a fair value gap. Is the gap invalidated?", o:["No, provided the candle bodies respect the level","Yes, any trade beyond the gap ends its validity","No, a gap can never be invalidated once it forms","Yes, unless price returns within the same session"], a:0, e:"He answers this directly: it does not invalidate it. Look at the body of the candle, which respects the level, and permit a greater level of imperfection in volatile price delivery." },
  { q:"What makes a fair value gap an even better entry?", o:["Sell side liquidity below a short-term low in it","A round number sitting exactly at its midpoint","It forming during the New York lunch hour itself","Its size exceeding the average daily range value"], a:0, e:"The gap is even better when there is sell side liquidity resting below a short-term low that taps into it, since you can use that low, or one tick below, as the entry." },
  { q:"Why are the setups sneaky after price runs the overnight stops?", o:["They will not offer the stopped-out traders a re-entry","The exchange widens spreads after a liquidity sweep","Volume dries up completely for the rest of the day","The algorithm pauses until the following day's open"], a:0, e:"Once the stops are run there is no reason for price to go back down there. They do not want to give those traders another chance to get back in, so the continuation setups are subtler." },
  { q:"Which reference does he use as the day's opening price?", o:["8:30 in the morning, drawn forward in time","The midnight New York open of the daily candle","The 9:30 equities bell, drawn forward in time","The prior session's 4:30 in the afternoon close"], a:0, e:"Asked where the opening price is, he answers that he likes 8:30 and draws that level out in time, then checks whether price went below it and into the imbalance." }
]
