[
  { q:"When is a short-term swing high being taken out actually significant?",
    o:["Only if the run before it took out sell stops",
       "Only if the candle closes above the old high",
       "Only if it happens inside the London session",
       "Only if volume expands on the breakout candle"],
    a:0,
    e:"The break is significant only on the basis that liquidity has been taken out of the marketplace — the run down before it has to have traded into sell stops below an old low, a double bottom, or something retail would view as support. Bearish is the mirror: a short-term low matters only because buy stops were taken first." },

  { q:"The swing high has just been taken. What do you watch for next?",
    o:["The next candle leaving a fair value gap",
       "The next candle closing above that high",
       "A retest of the swing low that formed",
       "A second high forming at the same level"],
    a:0,
    e:"Price only has to trade above the high — it does not need to close above it. Once that candle closes, monitor the next one: if it creates a fair value gap, that gap is the earliest place you would look to trade." },

  { q:"What is an order block?",
    o:["A change in the state of delivery",
       "A zone of unfilled institutional orders",
       "Any down-closed candle before a rally",
       "The midpoint of a completed price leg"],
    a:0,
    e:"An order block is a change in the state of delivery. It is not the case that every down-closed candle is a bullish order block and every up-closed candle a bearish one — a whole series of candles driving into liquidity is one continuous order block." },

  { q:"Which price on that series of candles is the level you reference?",
    o:["The opening price of the first candle in it",
       "The closing price of the last candle in it",
       "The midpoint of that series' high and low",
       "The lowest wick printed by the whole series"],
    a:0,
    e:"The reference is the opening price of the candle that began the series, extended out in time — the algorithm remembers that opening, which is why the level is sensitive. The buy is that opening price inside the fair value gap, plus spread, as a limit order." },

  { q:"What does 'internal range liquidity' mean?",
    o:["A short-term high or low in a leg being retraced",
       "The stops resting outside the whole weekly range",
       "The volume traded between the open and midpoint",
       "A pool of stops built over several trading days"],
    a:0,
    e:"Internal range liquidity is a short-term high or low sitting inside a price leg you are retracing back into, with stops above or below it — or an imbalance in that same range of price action. That's all it means." },

  { q:"Which session highs and lows should be marked, in New York time?",
    o:["London 2–5 am, New York 7–10 am, Asia 7–9 pm",
       "London 3–6 am, New York 8–11 am, Asia 6–8 pm",
       "London 1–4 am, New York 9–12 pm, Asia 8–10 pm",
       "London 2–6 am, New York 7–11 am, Asia 5–9 pm"],
    a:0,
    e:"Always set times to New York local time: London 2:00–5:00 am, New York 7:00–10:00 am and Asia 7:00–9:00 pm, plus any intraday high or low forming right before equities open at 9:30. The market will probably sweep above or below them." }
]
