[
  { q:"Which time window is the New York open killzone for FX pairs?", o:["7:00am to 10:00am New York time","8:30am to 11:00am New York time","Midnight to 8:30am New York time","9:30am to the 4:00pm close"], a:0, e:"FX uses 7:00 to 10:00. Index futures use 8:30 to 11:00, and he'll still take an index trade up to 10:40 or 10:45." },
  { q:"When the 8:30am opening price is lower than the midnight open and you are bearish, which do you use?", o:["The lower of the two, the 8:30 open","The midnight open, always","Whichever is nearer current price","The average of the two prices"], a:0, e:"Use the lower one, because you want to set the minimum threshold for a Judas swing or market protraction to the upside. Bullish, it reverses — look for a move below the 8:30 open." },
  { q:"What does a 10:00am high impact news driver do to the FX killzone?", o:["Extends it into the 11:00–11:30 window","Cancels trading for the rest of the day","Shifts the whole killzone one hour earlier","Restricts entries to the 10:00 candle only"], a:0, e:"The volatility it brings extends the New York session killzone into 11:00 / 11:30. Canadian dollar traders get the same allowance for the 10:30 crude oil inventory number." },
  { q:"Why does he say he ignores the actual news figure?", o:["He only wants the volatility it injects","The data is released to insiders first","Forex quotes are unaffected by data","The numbers are revised too often"], a:0, e:"\"I don't care about the raw data, I don't care what the expectation is.\" The algorithm uses the injection of volatility to reprice to levels that let those in the know participate." },
  { q:"Which price levels does he call institutional price levels?", o:["The 00, 20, 50 and 80 levels","Every 5-pip increment on the pair","Only the daily high and low","The 25, 33 and 66 percent levels"], a:0, e:"The big figure and the 00, 20, 50 and 80 levels are influential because a great deal of commerce and business transactions settle around them — which is where the liquidity is." },
  { q:"Why does he keep his own charts clean while telling students not to?", o:["Drawn levels force a bias he wants to avoid","Chart software slows down with annotations","He memorises every level in advance","Clean charts are required for recording"], a:0, e:"He wants the clarity to see when his premise is negated so he can reverse or step aside. Students still need annotations — relative equal highs, swing highs, intermediate term highs — to train their eyes to see it." },
  { q:"After three consecutive down close candles, what was his bias for the next daily candle?", o:["Bearish — sell-side liquidity was untouched","Bullish — the move was overextended","Neutral until the daily closed","Bullish, since buy stops were taken"], a:0, e:"Monday's low had not taken out the lower relative equal lows, so there was unfinished business below and the bias stayed bearish." },
  { q:"How did he identify the bearish order block price ran up into?", o:["Last up close candle after displacement and a gap","The candle with the highest wick of the day","The largest volume candle of the session","The open of the midnight candle itself"], a:0, e:"Displacement lower creates the fair value gap, and price returns to the last up close candle — that is the bearish order block. He uses its body, not the long tails and wicks." },
  { q:"How should you place the exit limit relative to your target level?", o:["Three to five pips short of it","Exactly on the level for the best fill","Ten pips beyond the level","At the level, then trail from there"], a:0, e:"Fluff the exit by three to five pips, ten if you're new — aiming at 1.0900 means a limit at 1.0905. You must account for the spread, and every broker can widen it." },
  { q:"Why does a trailing stop get taken out around a news driver?", o:["The buy stop supplies liquidity to sell into","News halts the book and gaps price","Brokers cancel resting orders at 10:00","Volatility filters reject the order"], a:0, e:"Your protective buy stop above recent swing highs floods the market with buyers paying a higher price — the counterparty smart money needs to sell short into. Every buyer has to have a seller." }
]
