[
  { q:"What makes an order block valid?", o:["An imbalance has to follow it","It must be a fresh, untouched zone","It must sit inside the killzone","It must be the highest candle body"], a:0, e:"\"What makes an order block valid — it has to have an imbalance. Without the imbalance, there is no order block.\" That requirement is also why this is not supply and demand, which insists on fresh zones." },
  { q:"Where does the stop go when the imbalance is very stretched out?", o:["At the top of that imbalance","One pip above the entry candle","At the midnight opening price","Below the fair value gap low"], a:0, e:"\"Whenever you have a big range like that, my stop can place right there\" — the top of the imbalance, rather than reaching all the way up to the swing high." },
  { q:"Which chart does he call his bellwether?", o:["The 15-minute chart","The five-minute chart","The hourly chart","The daily chart"], a:0, e:"The 15-minute is the chart he keeps returning to all day: it informs managing a position, stalking a setup, and it helps him trust his intraday bias." },
  { q:"Why did price never reach the last up close candle?", o:["The parent 15-minute imbalance stopped it","The killzone window had already closed","The daily bias had flipped bullish","The five-minute gap was already filled"], a:0, e:"The higher timeframe imbalance is parent to the subordinate lower timeframes — the 15-minute range stops the run there, so there is no necessity to trade into that last candle." },
  { q:"What do you do if the limit order has not filled by 11:30?", o:["Pull the order and wait","Leave it good till cancelled","Move it up to chase price","Convert it to a market order"], a:0, e:"\"What happens if it doesn't fill you by 11:30? Pull the order.\" You want to enter on the day the setup forms; left open it can fill at a bad time of day and then run through the highs." },
  { q:"Why does he warn against short-term trading gold?", o:["It is an event driven market","It has no daily fair value gaps","Its killzones run on London time","It only trades in a discount array"], a:0, e:"Gold usually needs a geopolitical driver to move; otherwise it is highly manipulated, with lots of stop hunts and consolidations — not the ideal market to trade aggressively while learning." },
  { q:"How many days' highs and lows should you highlight?", o:["The last three days","The last three weeks","The last three hours","The last three months"], a:0, e:"\"Highlight the previous day's highs and lows and do that for the last three days.\" Do it and you'll see a plethora of setups and liquidity pools you can attack — \"you're never going to run out of trades, ever.\"" },
  { q:"Can you enter a brand new position from your phone?", o:["No — the data is compressed","Yes, if the killzone is open","Yes, on the 15-minute chart","No — brokers forbid it there"], a:0, e:"You can manage a trade on a phone, but entering a brand new position on one, no: \"you don't see enough data, it's just too compressed\" and you need to see the lay of the land. He has not met anyone consistently profitable, trading millions, who does it from a phone." },
  { q:"The low threshold entry carries the highest risk in pips. What sets the money at risk?", o:["The leverage you allocate","The number of pips risked","The size of the fair value gap","The killzone you entered in"], a:0, e:"The higher risk is \"in terms of number of pips, not in terms of the amount of money, because that part is always controlled by you the trader — you can manage the amount of leverage you're using.\" Leverage is the thing traders abuse most." }
]
