[
  { q:"On a bullish afternoon continuation, what usually gets swept first?", o:["The lows made during the New York lunch hour","The overnight Asian session high","The previous week's opening price","The equal highs left from the morning"], a:0, e:"\"Many times when there's an afternoon continuation to the upside, the lows at lunch time will get swept\" — noon to one — and price dug further into an imbalance below them." },
  { q:"How close did the pre-2pm Judas swing come to the morning high?", o:["One tick — a quarter of a point short","Exactly level, to the tick","About twenty points short of it","It exceeded it by a full handle"], a:0, e:"The morning high was 12,535.75 and the afternoon run reached 12,535.50 — one quarter of a point, one tick, short of it — then it broke lower with no model short available." },
  { q:"What is said to happen to morning longs during that sweep?", o:["Their trailed stops sit below the lunch lows","They are filled again at a better average","They are unaffected because they exited at noon","They add size as the imbalance is tagged"], a:0, e:"Longs from the morning had trailed their stop losses below the lunch lows, so the sweep takes them out — the point being that they are not permitted to profit on the real move to 12,553.25." },
  { q:"What happens at 3 o'clock in this example?", o:["Algorithms spool price toward the liquidity","The lunch consolidation range begins","The Fed chairman's remarks are released","The order block is invalidated for the day"], a:0, e:"At three o'clock the algorithms start to spool price in the direction of the liquidity — the 12,553.25 level — which it then consolidates below and hammers into." },
  { q:"Why does he draw attention to the afternoon sell-off that gave no setup?", o:["The pattern won't appear where delivery is unlikely","It proves the model only works on Fed days","It shows a short was available but he missed it","It confirms the imbalance had been invalidated"], a:0, e:"The market sold off but the model produced no setup — when the market is in sync, these algorithmic principles will not appear in markets that are not likely to deliver, though he adds plainly that it will not work all the time." },
  { q:"How does he describe his own entry on this trade?", o:["A really poor entry, taken below the equal lows","A textbook fill at the middle of the gap","A limit order filled at the exact session low","An add to a position carried from the morning"], a:0, e:"\"I got one off as far as a long, and a really poor entry\" — he was focused simply on being below the relative equal lows, having missed the intended imbalance entry because he wasn't quick enough." },
  { q:"What did he annotate about the level price stalled at before lifting?", o:["It was not resistance — it would lift off","It was the day's high and should be sold","It marked the end of the afternoon session","It was the correct place to trail a stop"], a:0, e:"He made the annotation live that the area was not resistance and shouldn't be read that way — \"it's going to lift off from here\" — and price went to an order block and rallied." },
  { q:"Which upside level does he name as the next one to anticipate?", o:["12,624 even, past the sloppy area above","12,535.75, the morning session high","12,417.75, where the long was filled","The relative equal lows made at lunch"], a:0, e:"Reaching 12,553.25 is not a call for a high; the area immediately above is sloppy, so he points to the 12,624 even high as the next one worth anticipating and studying." }
]
