[
  { q:"What is the first check in daily rebalance theory?", o:["Is there a fair value gap in the last three days?","Is the daily candle bullish or bearish in body?","Has the weekly opening price been traded through?","Is the current day's range larger than average?"], a:0, e:"The routine traces back to studying the last three days' open, high, low and close — look back over them and ask whether there is a fair value gap." },
  { q:"When the last three days hold no fair value gap, what level does he use instead?", o:["The previous day's low, to rebalance the drop","The midpoint of the three-day range","The weekly high above the current price","The opening price of the current session"], a:0, e:"With no gap in the last three days, he goes back to the previous day's low — Friday's — and treats it as the level a retracement can reach to rebalance Monday's large-range decline." },
  { q:"Why is running the buy side <em>before</em> the low below gets taken important?", o:["It keeps the move inside a bearish context","It shows the sell side has already been consumed","It confirms the seasonal tendency has expired","It marks the exact high of the trading week"], a:0, e:"Running above buy-side liquidity at 9:30 without that low having been taken out is bearish, because it's within the context of the bias; going down to take the previous low first and then rallying is not." },
  { q:"After a displacement leg forms, what does the Fibonacci placed on its high and low decide?", o:["Whether the entry sits in a premium or discount","How many contracts the position should carry","Which timeframe the gap will appear on","Where the daily range is likely to close"], a:0, e:"Equilibrium came in at 4044.5; a gap below that would be selling in a discount, and the hard-line rule is that you must be at that level or higher — in a premium — to sell." },
  { q:"Where does the minimum stop go on the fair value gap entry?", o:["A tick or two above the candle creating the gap","At the equilibrium level of the displacement swing","Below the short-term low that was taken out","At the previous day's low being rebalanced"], a:0, e:"The rule is to use the high of the candle that creates the fair value gap — one or two ticks above it is sufficient; the ample alternative is above the swing high." },
  { q:"What does he say about markets in May for the index futures?", o:["They tend to be weak — a seasonal tendency","They rally reliably into the summer months","They range with no directional tendency at all","They only move on FOMC and payroll days"], a:0, e:"From about the last week of April into May, the S&amp;P, Nasdaq, Dow and Russell tend to be weak — generally, not always, but visible if you study old data." },
  { q:"Why should you not trail the stop aggressively once the trade moves your way?", o:["A strangled position never gets room to breathe","Brokers reject stops moved more than once","Trailing cancels the original limit order fill","It converts the trade into a discount entry"], a:0, e:"You have to hold with a certain measure of risk open; trailing so tight so quickly strangles the position and doesn't even give it the chance to move and breathe — the stop moves only after a larger shift in structure." },
  { q:"How long does he say serious study of this material should take?", o:["Six months — three back testing, then forward testing","Two weeks of watching the videos through twice","A full year before opening any demo account","One month, then straight into live funds"], a:0, e:"Three months of serious daily back testing, then two or three more months of forward testing — after six months with just this material he is confident you will have found your model." }
]
