[
  { q:"How is a breaker defined on the daily chart here?", o:["Low, high, low — the high in between","Two equal highs with a gap between","The largest down candle of the week","The close of the previous month"], a:0, e:"\"A breaker is a low, high, low — find the high in between, extending out in time\", and the market trades back down into it." },
  { q:"Price moved off a low and created a swing low. What is the bias?", o:["Bullish until the high above is taken","Bearish until the same low is retested","Neutral until a weekly close prints","Bullish only after the gap is filled"], a:0, e:"When price moves from a low and creates a swing low, it's easy to assume it wants to come back up to that high — bullish until that high is taken out." },
  { q:"Why is a retracement after taking that high described as logical?", o:["The rally left a fair value gap to fill","Highs always reverse the daily trend first","News is scheduled after every breakout","The breaker inverts once it is broken"], a:0, e:"A day or two of retracement is logical because a fair value gap was created; price trades down, fills it in, tests it and rallies." },
  { q:"What is the advice for Non-Farm Payroll Friday?", o:["Study the price action, don't trade it","Trade it small with a much wider stop","Trade only after the first hour has passed","Close the charts until Monday's open"], a:0, e:"He does not advise speculating on it. Instead, work out which side of liquidity price reaches for before 8:30, then watch the one- and five-minute charts — a study for liquidity purposes only." },
  { q:"Why did he take a trade on a day he tells everyone to avoid?", o:["To demonstrate why he avoids those days","Because his rules allow one such exception","The setup was far too good to pass on","A subscriber had challenged him to do it"], a:0, e:"\"I forced myself to engage… because I want to teach you why I avoid these days\" — his precision drops precipitously on them." },
  { q:"What should you do if you have not made anything by Wednesday's New York session?", o:["Take no trades and just observe","Increase the size to catch up","Switch to a different market instead","Trade only the Friday session"], a:0, e:"He presses students to stop trading by the New York session on Wednesday either way — sit with the desire to trade and do nothing, which forges discipline and patience." },
  { q:"Why is one-minute price action not \"noise\"?", o:["It repeats the daily shape at smaller scale","Every tick there is a real institutional order","Noise only exists on tick-by-tick charts","The exchange filters the noise out of it"], a:0, e:"\"It's doing what it does on the daily chart, just being represented on a smaller interval\" — accumulation, manipulation, distribution." },
  { q:"How should a journal annotation be phrased?", o:["As though you saw it in advance","As a record of what you missed","As a checklist of rules broken","As a forecast for the next day"], a:0, e:"Phrase it like you saw it beforehand — self talk that tricks the subconscious into treating it as experience you actually had, borrowed for the study." },
  { q:"What must never go into those journal entries?", o:["Negative or self-critical remarks","Exact times and price levels","Screenshots of the chart markup","Notes about the higher timeframe"], a:0, e:"Never write \"I wish I'd seen this\" or \"I was foolish\" — entries are for reflecting on later, so they must stay factual and positive." },
  { q:"What did he say separates his students who fail?", o:["They refuse to do the journaling work","They trade far too small to learn from","They watch too few of his videos","They use the wrong charting platform"], a:0, e:"\"Watching my videos will not do it for you… If you fail under my tutelage, it's because you don't do this.\" That is where the tailspin into failure starts." }
]
