[
  { q:"What three things make a bullish order block high probability?", o:["Down close candle, imbalance, buy-side draw","Engulfing candle, high volume, round number","Three down candles, a doji, then a gap up","Trend line touch, oversold reading, retest"], a:0, e:"It is the down close candle, plus the imbalance left as price moves away from it, plus the narrative that price is going higher for buy-side liquidity. He is explicit that no engulfing candle is required." },
  { q:"Why does he take these executions in a demo account?", o:["He won't risk the gain already banked","Demo fills are better than live fills","His live broker was closed that morning","The setup was too small for real money"], a:0, e:"He is bearish but the market already delivered his move, and with the uncertainty around Ukraine he will not risk the February live gain — losing it would eat at him all through March. The demo also keeps him compliant and plugged into the tape." },
  { q:"What is the initial move into the 9:30am equities open usually?", o:["A Judas swing in the wrong direction","The true direction for the whole day","A low-volume drift with no meaning","The safest entry of the session"], a:0, e:"The initial move going into the 9:30am open is technically the incorrect move — a Judas swing. Don't chase it, and don't chase price higher right before the open either." },
  { q:"How does he size a pyramided position?", o:["Largest first, then smaller add-ons","Smallest first, then larger add-ons","Equal size on every single entry","Doubling the size at each new entry"], a:0, e:"He bought three micros, then two, then one — the biggest position at the initial entry so later adds have that equity behind them. Buying one then two then three is an inverted pyramid: balancing on its point, wobbly and unstable." },
  { q:"Once price trades above a down close candle's high, where does the stop stay?", o:["Below that candle's low","At the entry price, breakeven","Just under the current candle","Above the most recent swing high"], a:0, e:"Price can dig back into that candle because it will act as an order block. Put the stop inside that retracement zone and you are stopped out prematurely — the stop only rises once a set of down close candles has been taken out." },
  { q:"What does an intermediate term low tell you about the trade?", o:["It should hold until the objective is met","It marks the end of the bullish leg","It is where partial profits must be taken","It invalidates the higher timeframe read"], a:0, e:"Once the gap fills, the low created is an intermediate term low, and it should not be taken out until the objective is reached. That is what lets him sit through the retracements." },
  { q:"What happens as price nears the profit objective?", o:["It only retraces shallowly into the gap","It fully rebalances the order block first","It stalls until the next session opens","It always sweeps the entry low again"], a:0, e:"When price is that close to the objective it generally doesn't like to come all the way back into the order block to rebalance — the algorithm allows only a small retracement inside the fair value gap before running to target." },
  { q:"What does he say about missing a trade?", o:["Another is likely the next trading day","You must take the next setup you see","Drop to a lower timeframe to catch it","Widen your stop so it can't happen again"], a:0, e:"These setups likely form every day and certainly every week, but that is not an invitation to trade daily. If you miss one, you're likely to find another on the next trading day." }
]
